---
name: YAML

"on": [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Determine if files changed
        uses: fkirc/skip-duplicate-actions@v3.4.1
        id: skip_check
        with:
          paths: '["**.yaml", "**.yml"]'

      - name: Checkout code
        uses: actions/checkout@v2
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - name: Run yamllint
        uses: actionshub/yamllint@1.0.0
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Determine if files changed
        uses: fkirc/skip-duplicate-actions@v3.4.1
        id: skip_check
        with:
          paths: '["**.yaml", "**.yml"]'

      - name: Checkout code
        uses: actions/checkout@v2
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - name: prettier
        uses: creyD/prettier_action@v3.3
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          dry: true
          prettier_options: "--check **.{yml,yaml}"
